
datasource:
    url: jdbc:h2:./data/testdb # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
h2:
    console:
      enabled: true # Enable H2 console
      path: /h2-console # Access H2 console at /h2-console

server:
  port: 9097 # Optional: Change server port if needed

spring:
  application:
    name: EmployeeService

